### ISSUE TITLE
ekcp fails to start

### ISSUE THREAD

**Issue by danielvaughan** [mudler/ekcp#6]
I initially setup ekcp and it was working fine. 

I successfully created a test cluster using

```
curl -d "name=test" -X POST http://127.0.0.1:8030/new
```

to try it out and did `docker-compose down' and everything appeared to be cleared away.

However a couple of hours later I started again with `docker-compose up -d` but the ekcp container failed straight away with the error:

```
panic: Could not connect with kubeconfig: failed to get kube config: stat /root/.kube/kind-config-test: no such file or directory

goroutine 1 [running]:
main.main()
        /go/src/github.com/mudler/ekcp/main.go:18 +0xe77
```

It is like it has remembered the test cluster even though there is no '/root/.kube/kind-config-test' in the docker image and I can't see any other place that state is stored, volumes etc.

Turns out of course that this was due to the cluster still being in kind but the config not being in the new container. Perhaps this could be mentioned in docs to help people like me.

**Comment by mudler** [comment]
Sorry for being late at this, completely oversee the issue. 

Yes, at the moment EKCP doesn't support this scenario, clusters that has been created with EKCP has to be deleted by EKCP or either you have to remove the dangling containers in the machine manually ( the one you can find in `docker ps -a` )

**Comment by mudler** [comment]
Thanks and sorry that you met this issue.. will create a note in the docs about this! On the other hand, this can be supported by EKCP as well, will document the workaround meanwhile this gets handled internally

**Comment by mudler** [comment]
done in https://github.com/mudler/ekcp/commit/ad616e7fca3545c34507c3fb242b79b284ceb8a1, thanks for raising this up. Now that Kind actually support restarts (since 0.8.x) , we could have also start/stop in the api as well.

**Comment by mudler** [comment]
Created #7 and #8 as a follow-up! closing this, thanks :slightly_smiling_face:
